#!/bin/bash
##############################
### HERBSTLUFT MAIN CONFIG ###
##############################




# run
hc() {
    herbstclient "$@"
}


# STARTUP 

hc emit_hook reload

# unlock
hc unlock

# setup monitors
hc detect_monitors


# PANELS

# kill previously running panels
killall dzen2 &

# load panel settings
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start panel on each monitor
    "$panel" $monitor &
done


# SETTINGS

hc set tree_style '╾│ ├└╼─┐'
hc set wmname 'Herbstluftwm'
hc set auto_detect_monitors		1
hc set focus_follows_mouse		1
hc set focus_stealing_prevention	1
hc set mouse_recenter_gap		1
hc set pseudotile_center_threshold	0
hc set raise_on_click			1
hc set raise_on_focus			0
hc set raise_on_focus_temporarily	1
hc set smart_frame_surroundings		1
hc set smart_window_surroundings	0
hc set swap_monitors_to_get_tag		0

# load theme settings
source $HOME/.config/herbstluftwm/theme.sh


# RULES

# unrule
hc unrule -F

hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off
hc rule instance~'(.*X11-XDialogPeer.*)' pseudotile=on

# focus new clients
hc rule focus=on


# KEYBINDINGS

# remove all existing keybindings
hc keyunbind --all

# load keybindings
source $HOME/.config/herbstluftwm/keybindings.sh
